name: upstream

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 0 * * *'

  watch:
    types: [started]

jobs:
  autocard:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Sync with upstream
        if: github.repository_owner == 'idrblab'
        continue-on-error: false
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
        with:
          upstream_sync_repo: GCS-ZHN/socube-docs
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_pull_args: '-s recursive -Xtheirs'
